openapi: 3.0.0

info:
  description: ""
  version: 1.0.0
  title: デプロイテスト

x-amazon-apigateway-request-validators:
  all:
    validateRequestParameters: true
    validateRequestBody: true
  params-only:
    validateRequestParameters: true
    validateRequestBody: true
x-amazon-apigateway-request-validator: all

tags:
  - name: hello
    description: "hello world tag"

paths:
  /hello:
    get:
      tags:
        - hello
      x-amazon-apigateway-integration:
        uri: arn:aws:apigateway:ap-northeast-1:lambda:path/2015-03-31/functions/arn:aws:lambda:ap-northeast-1:867880594888:function:cpts-dev-lambda-HelloWorldFunction/invocations
        passthroughBehavior: when_no_match
        httpMethod: POST
        type: AWS_PROXY
      summary: hello world
      description: hello world を表示する
      responses:
        "200":
          description: "成功"
          content:
            application/json:
              schema:
                type: string
                example: "hello world"
