AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Timeout: 60
    Environment:
      Variables:
        TEST: dummy

Resources:
  LibsLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: cpts-libs-layer
      ContentUri: ../../cpts-libs-layer/src/
      CompatibleRuntimes:
        - python3.9
    Metadata:
      BuildMethod: python3.9

  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: func/
      Handler: app.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64
      Events:
        API:
          Type: Api
          Properties:
            Path: /hello
            Method: get
      Layers:
        - !Ref LibsLayer
